// Tests for the qnext_multislot_dispatch.allium contract.
//
// Generated by `allium:propagate qnext_multislot_dispatch.allium`.
// Each test maps to a contract or invariant in
// /home/llm/yarn-agentic/qnext_multislot_dispatch.allium; the comments
// name the spec construct and the obligation id from `allium plan`.
//
// Two test layers:
//
//   Layer 1 — kernel-level (this file, runnable today): asserts the
//             ggml_concat dtype-uniformity precondition that the CUDA
//             backend kernel guards at concat.cu:202. Reproduces the
//             exact crash signature observed in production
//             (snoop-20260505T111847) by issuing a heterogeneous-dtype
//             concat. RED today (the assert fires, the process aborts).
//             Once the layer-side fix lands, the test is satisfied
//             vacuously because the kernel no longer sees mismatched
//             operands; the test stays as a regression guard.
//
//   Layer 2 — layer-level (skeleton at end of file): asserts that
//             delta_net::build_layer_attn_linear produces concat
//             operands of uniform dtype across blocks for every
//             contracted batch shape. Requires a synthetic mini-layer
//             or a small loaded model — the bridge work is sketched
//             with TODOs.
//
// Build with -DGGML_CUDA=ON; runs only when CUDA is available.

#include "ggml.h"
#include "ggml-alloc.h"
#include "ggml-backend.h"
#include "ggml-cuda.h"

#include <cassert>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <vector>

namespace {

// ---------------------------------------------------------------------
// Test infrastructure — minimal CUDA backend + cgraph runner.
// Mirrors the pattern in test-q4-0-ar16-cuda.cpp.
// ---------------------------------------------------------------------

struct cuda_runner {
    ggml_backend_t backend = nullptr;
    ggml_context * ctx     = nullptr;
    std::vector<uint8_t> buf;

    cuda_runner() {
        backend = ggml_backend_cuda_init(0, nullptr);
        if (!backend) {
            fprintf(stderr, "ggml_backend_cuda_init failed\n");
            std::exit(2);
        }
        struct ggml_init_params params = {
            /* .mem_size   = */ 16 * 1024 * 1024,
            /* .mem_buffer = */ nullptr,
            /* .no_alloc   = */ true,
        };
        ctx = ggml_init(params);
        assert(ctx != nullptr);
    }

    ~cuda_runner() {
        if (ctx)     ggml_free(ctx);
        if (backend) ggml_backend_free(backend);
    }

    // Allocate every tensor in `ctx` to `backend`, build the supplied
    // cgraph, and run it. Returns true on completion, false on failure.
    bool run(ggml_cgraph * gf) {
        ggml_backend_buffer_t buf = ggml_backend_alloc_ctx_tensors(ctx, backend);
        if (!buf) {
            fprintf(stderr, "ggml_backend_alloc_ctx_tensors failed\n");
            return false;
        }
        const auto status = ggml_backend_graph_compute(backend, gf);
        const bool ok = (status == GGML_STATUS_SUCCESS);
        ggml_backend_buffer_free(buf);
        return ok;
    }
};

// Fill a tensor with a deterministic ramp on host, copy to device.
void fill_ramp_f32(ggml_backend_t backend, ggml_tensor * t, float base) {
    const size_t n = ggml_nelements(t);
    std::vector<float> data(n);
    for (size_t i = 0; i < n; ++i) data[i] = base + (float) i;
    ggml_backend_tensor_set(t, data.data(), 0, n * sizeof(float));
}

// ---------------------------------------------------------------------
// Test 1 — GgmlConcatOperands.SrcDstDtypeUniform — POSITIVE
//
// Spec construct: contract GgmlConcatOperands @invariant SrcDstDtypeUniform
// Obligation:     contract-signature.GgmlConcatOperands.invoke
//
// Two F32 tensors of differing dim-1 length, concat'd on dim 1, must
// run to completion on CUDA. This is the in-spec case.
// ---------------------------------------------------------------------
bool test_concat_uniform_f32() {
    cuda_runner r;

    const int64_t n_embd = 32;
    const int64_t blk_a  = 5;
    const int64_t blk_b  = 3;

    ggml_tensor * a = ggml_new_tensor_2d(r.ctx, GGML_TYPE_F32, n_embd, blk_a);
    ggml_tensor * b = ggml_new_tensor_2d(r.ctx, GGML_TYPE_F32, n_embd, blk_b);
    ggml_set_name(a, "blk_a");
    ggml_set_name(b, "blk_b");

    ggml_tensor * out = ggml_concat(r.ctx, a, b, /*dim*/ 1);
    ggml_set_name(out, "out");

    ggml_cgraph * gf = ggml_new_graph(r.ctx);
    ggml_build_forward_expand(gf, out);

    fill_ramp_f32(r.backend, a, 0.0f);
    fill_ramp_f32(r.backend, b, 1000.0f);

    const bool ok = r.run(gf);
    if (!ok) {
        fprintf(stderr, "test_concat_uniform_f32: graph_compute failed\n");
        return false;
    }
    if (out->ne[1] != blk_a + blk_b) {
        fprintf(stderr, "test_concat_uniform_f32: out->ne[1]=%lld, want %lld\n",
                (long long) out->ne[1], (long long) (blk_a + blk_b));
        return false;
    }
    return true;
}

// ---------------------------------------------------------------------
// Test 2 — GgmlConcatOperands.SrcDstDtypeUniform — NEGATIVE
//
// Spec construct: contract GgmlConcatOperands @invariant SrcDstDtypeUniform
// Obligation:     contract-signature.GgmlConcatOperands.invoke
//
// Two tensors of DIFFERENT dtype concat'd on CUDA. Documents the
// kernel-level precondition that the production crash violates.
//
// Status today: the call to ggml_concat at graph build time succeeds
// (ggml.c does not validate types), and ggml_backend_graph_compute
// then aborts the process via GGML_ASSERT in concat.cu:202. The test
// process can't recover, so it can't directly assert "abort happens";
// instead it documents the expected failure mode. Run manually via
// the standalone target to reproduce the production crash signature
// without needing the 27B model.
//
// Once the layer-level fix lands, no caller in the production code
// path issues mismatched-dtype concat, so this test's negative case
// is purely a contract guard. The kernel assert is a backstop.
//
// To run: env QNEXT_RUN_CONCAT_NEGATIVE=1 ./test-qnext-multislot-dispatch
// (default skipped to keep CI green; the abort is intentional).
// ---------------------------------------------------------------------
bool test_concat_mismatched_dtypes_aborts() {
    if (std::getenv("QNEXT_RUN_CONCAT_NEGATIVE") == nullptr) {
        printf("test_concat_mismatched_dtypes_aborts: SKIPPED (set QNEXT_RUN_CONCAT_NEGATIVE=1 to run)\n");
        return true;
    }

    cuda_runner r;

    const int64_t n_embd = 32;
    const int64_t blk_a  = 5;
    const int64_t blk_b  = 3;

    ggml_tensor * a = ggml_new_tensor_2d(r.ctx, GGML_TYPE_F32, n_embd, blk_a);
    ggml_tensor * b = ggml_new_tensor_2d(r.ctx, GGML_TYPE_F16, n_embd, blk_b);
    ggml_set_name(a, "blk_a_f32");
    ggml_set_name(b, "blk_b_f16");

    // ggml_concat does not validate at construction (ggml.c:6927-6960).
    // The result tensor takes a's type; the CUDA kernel guard at
    // concat.cu:202 catches the mismatch at execution.
    ggml_tensor * out = ggml_concat(r.ctx, a, b, /*dim*/ 1);
    ggml_set_name(out, "out_mismatched");

    ggml_cgraph * gf = ggml_new_graph(r.ctx);
    ggml_build_forward_expand(gf, out);

    fill_ramp_f32(r.backend, a, 0.0f);
    // b is F16, fill via host side then upload as raw bytes.
    {
        const size_t n = (size_t) n_embd * blk_b;
        std::vector<uint16_t> raw(n, 0);
        ggml_backend_tensor_set(b, raw.data(), 0, n * sizeof(uint16_t));
    }

    fprintf(stderr, "test_concat_mismatched_dtypes_aborts: about to run, "
            "expecting GGML_ASSERT abort in concat.cu:202\n");
    const bool ok = r.run(gf);
    // If we reach this line at all, the kernel assert did NOT fire,
    // which would itself be a contract violation (silent corruption).
    fprintf(stderr, "test_concat_mismatched_dtypes_aborts: graph_compute returned ok=%d "
            "WITHOUT aborting — this is a CONTRACT VIOLATION, the kernel "
            "guard is missing or has been weakened\n", ok ? 1 : 0);
    return false;
}

// ---------------------------------------------------------------------
// Test 3 — DtypeUniformAcrossBlocks (system invariant) — SKELETON
//
// Spec construct: invariant DtypeUniformAcrossBlocks
// Obligation:     invariant-property.DtypeUniformAcrossBlocks
//
// THIS IS THE BUG REPRO. Contract: drive a heterogeneous batch
// (e.g. token_seq_ids = [A, A, A, B, B]) through
// delta_net::build_layer_attn_linear; assert that the per-block
// LinearAttnLayerBuild outputs feeding the ggml_concat at
// src/llama-delta-net.cpp:689 have identical dtype.
//
// Layer-level reproduction needs one of:
//
//   (a) A tiny synthetic Qwen3-Next layer set up by hand. Requires
//       fabricating ssm_conv1d, ssm_dt, ssm_a, ssm_norm, ssm_out
//       weights at minimal sizes; building an llama_context shim;
//       calling delta_net::build_layer_attn_linear with a fake
//       cur tensor + inp_out_ids. Substantial setup; deferred.
//
//   (b) A small loaded model exercising the path via the public
//       llama API. Requires a mini Qwen3-Next-shaped GGUF (~100 MB
//       budget) plus a server harness like scripts/test-mtp-multislot.sh
//       that drives heterogeneous prompts. The 27B model already
//       crashes the production server reliably; (b) is the
//       deterministic version of that.
//
// Recommended bridge (per allium:propagate guidance):
//   Build a minimal Qwen3-Next-shaped GGUF for testing. The smallest
//   coherent shape is ~1 layer × 1 head × tiny n_embd. Then drive
//   it through llama_decode with two slots and heterogeneous prompts.
//   The Phase 32 test scripts/test-mtp-state-isolation.sh is the
//   closest analog — it drives the 27B model. The propagate
//   obligation is to extend it to a model size that fits CI.
//
// Until that bridge exists, this test reports SKIPPED and the
// production server's snoop-recorded crashes serve as the
// integration-level evidence.
// ---------------------------------------------------------------------
bool test_dtype_uniform_across_blocks_layer() {
    printf("test_dtype_uniform_across_blocks_layer: SKIPPED — needs synthetic mini-Qwen3-Next or test GGUF; see file comments for bridge plan\n");
    return true;
}

// ---------------------------------------------------------------------
// Test 4 — InpOutIdsPerBlockSliceOrDeferred (system invariant) — SKELETON
//
// Spec construct: invariant InpOutIdsPerBlockSliceOrDeferred
// Obligation:     invariant-property.InpOutIdsPerBlockSliceOrDeferred
//
// Source-level static check stand-in: assert that the per-block call
// site at src/llama-delta-net.cpp:687 either
//   - slices inp_out_ids before passing, OR
//   - passes nullptr (gather deferred past the join).
//
// As written today the call passes inp_out_ids verbatim — the
// divergence the weed report flagged. A grep-based check is brittle
// but it captures the contract until a runtime-observable equivalent
// is wired in via Test 3's bridge.
//
// Currently: SKIPPED. The static check belongs to a future tooling
// pass; the runtime evidence is captured by Test 3 once that lands.
// ---------------------------------------------------------------------
bool test_inp_out_ids_per_block() {
    printf("test_inp_out_ids_per_block: SKIPPED — needs Test 3's bridge or a static analyzer\n");
    return true;
}

// ---------------------------------------------------------------------
// Test 5 — NoAbortOnContractedPatterns (system invariant) — INTEGRATION
//
// Spec construct: invariant NoAbortOnContractedPatterns
// Obligation:     invariant-property.NoAbortOnContractedPatterns
//
// Server-level integration test. For each pattern (SINGLE,
// CONTIGUOUS_BLOCKS) and each block count up to
// config.max_blocks_under_contract, drive a real heterogeneous batch
// and assert the server process stays alive.
//
// Implementation: scripts/test-mtp-multislot.sh exists for SINGLE
// at np=1,2,4,8 (Phase 32 acceptance). A new script,
// scripts/test-qnext-heterogeneous-batch.sh, would drive
// CONTIGUOUS_BLOCKS by submitting parallel POSTs whose prompts
// differ in length within the same scheduler step.
//
// SKIPPED here — out of scope for a unit test. Tracked in the spec
// at OQ-2 and as a follow-up to the layer-level fix.
// ---------------------------------------------------------------------
bool test_no_abort_on_contracted_patterns() {
    printf("test_no_abort_on_contracted_patterns: SKIPPED — see scripts/test-qnext-heterogeneous-batch.sh (TODO)\n");
    return true;
}

}  // namespace

// ---------------------------------------------------------------------

int main() {
    int passed = 0;
    int failed = 0;

    auto run = [&](const char * name, bool (*fn)()) {
        printf("=== %s ===\n", name);
        const bool ok = fn();
        if (ok) {
            printf("PASS %s\n\n", name);
            ++passed;
        } else {
            printf("FAIL %s\n\n", name);
            ++failed;
        }
    };

    run("test_concat_uniform_f32",                     test_concat_uniform_f32);
    run("test_concat_mismatched_dtypes_aborts",        test_concat_mismatched_dtypes_aborts);
    run("test_dtype_uniform_across_blocks_layer",      test_dtype_uniform_across_blocks_layer);
    run("test_inp_out_ids_per_block",                  test_inp_out_ids_per_block);
    run("test_no_abort_on_contracted_patterns",        test_no_abort_on_contracted_patterns);

    printf("=== summary: %d passed, %d failed ===\n", passed, failed);
    return failed == 0 ? 0 : 1;
}
